-- =============================================================
-- Puzzle Suggestions Schema
-- Stores AI-generated puzzle options for admin review
-- Generated by the morning puzzle agent cron job
-- =============================================================

CREATE TABLE IF NOT EXISTS puzzle_suggestions (
  id SERIAL PRIMARY KEY,
  target_date DATE NOT NULL,
  puzzle_type VARCHAR(20) NOT NULL,      -- 'tandem', 'mini', 'soup', 'reel'
  option_number SMALLINT NOT NULL,       -- 1-based option index
  puzzle_data JSONB NOT NULL,            -- Full puzzle payload (game-specific)
  quality_score NUMERIC(3,1),            -- AI-assessed quality 1-10
  quality_notes TEXT[],                  -- Array of quality check results
  status VARCHAR(20) DEFAULT 'pending',  -- 'pending', 'selected', 'dismissed'
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  reviewed_by VARCHAR(50),
  UNIQUE(target_date, puzzle_type, option_number)
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_suggestions_date_type
  ON puzzle_suggestions(target_date, puzzle_type);

CREATE INDEX IF NOT EXISTS idx_suggestions_status
  ON puzzle_suggestions(status, target_date DESC);

CREATE INDEX IF NOT EXISTS idx_suggestions_generated
  ON puzzle_suggestions(generated_at DESC);

-- RLS: service role only (cron + admin routes use service role key)
ALTER TABLE puzzle_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "suggestions_service_role" ON puzzle_suggestions
  FOR ALL USING (true) WITH CHECK (true);

COMMENT ON TABLE puzzle_suggestions IS 'AI-generated puzzle options for admin review (morning agent)';
COMMENT ON COLUMN puzzle_suggestions.puzzle_type IS 'Game type: tandem, mini, soup, reel';
COMMENT ON COLUMN puzzle_suggestions.option_number IS '1-based index for this option within (date, type)';
COMMENT ON COLUMN puzzle_suggestions.puzzle_data IS 'Full puzzle payload in game-specific format';
COMMENT ON COLUMN puzzle_suggestions.quality_score IS 'AI-assessed quality score 1.0-10.0';
COMMENT ON COLUMN puzzle_suggestions.status IS 'Review status: pending, selected, dismissed';
