/**
 * @jest-environment node
 */

/**
 * CrosswordGenerator unit tests
 *
 * Tests the CSP solver: grid filling, constraint propagation,
 * candidate generation, seed word support, and quality scoring.
 */

import CrosswordGenerator from '../server/CrosswordGenerator';
import WordIndex, { getWordIndex, clearWordIndexCache } from '../server/WordIndex';

/**
 * Build a test WordIndex with a known set of words.
 * Includes enough words to fill 5x5 grids reliably.
 */
function buildTestIndex() {
  const index = new WordIndex();

  // 2-letter words
  const twoLetterWords = [
    'AT',
    'BE',
    'DO',
    'GO',
    'HE',
    'IF',
    'IN',
    'IS',
    'IT',
    'ME',
    'MY',
    'NO',
    'OF',
    'ON',
    'OR',
    'SO',
    'TO',
    'UP',
    'US',
    'WE',
  ];

  // 3-letter words
  const threeLetterWords = [
    'ACE',
    'ACT',
    'ADD',
    'AGE',
    'AID',
    'AIM',
    'AIR',
    'ALL',
    'AND',
    'ANT',
    'APE',
    'ARC',
    'ARE',
    'ARK',
    'ARM',
    'ART',
    'ATE',
    'AWE',
    'BAD',
    'BAG',
    'BAN',
    'BAR',
    'BAT',
    'BED',
    'BET',
    'BIG',
    'BIT',
    'BOW',
    'BOX',
    'BUS',
    'BUT',
    'BUY',
    'CAB',
    'CAN',
    'CAP',
    'CAR',
    'CAT',
    'COP',
    'COW',
    'CRY',
    'CUP',
    'CUT',
    'DAD',
    'DAM',
    'DAY',
    'DID',
    'DIG',
    'DIM',
    'DIP',
    'DOG',
    'DOT',
    'DRY',
    'DUG',
    'DUO',
    'EAR',
    'EAT',
    'EEL',
    'EGG',
    'ELF',
    'ELM',
    'END',
    'ERA',
    'EVE',
    'EWE',
    'EYE',
    'FAN',
    'FAR',
    'FAT',
    'FIG',
    'FIN',
    'FIT',
    'FLY',
    'FOG',
    'FOR',
    'FOX',
    'FRY',
    'FUN',
    'FUR',
    'GAP',
    'GAS',
    'GET',
    'GOD',
    'GOT',
    'GUM',
    'GUN',
    'GUT',
    'GUY',
    'HAD',
    'HAM',
    'HAS',
    'HAT',
    'HEN',
    'HER',
    'HID',
    'HIM',
    'HIS',
    'HIT',
    'HOG',
    'HOP',
    'HOT',
    'HOW',
    'HUG',
    'ICE',
    'ICY',
    'ILL',
    'INK',
    'INN',
    'ION',
    'IRE',
    'ITS',
    'IVY',
    'JAM',
    'JAR',
    'JAW',
    'JAY',
    'JET',
    'JOB',
    'JOG',
    'JOT',
    'JOY',
    'JUG',
    'KIT',
    'KEY',
    'LAP',
    'LAW',
    'LAY',
    'LED',
    'LEG',
    'LET',
    'LID',
    'LIE',
    'LIT',
    'LOG',
    'LOT',
    'LOW',
    'MAD',
    'MAN',
    'MAP',
    'MAT',
    'MAY',
    'MEN',
    'MET',
    'MIX',
    'MOB',
    'MOM',
    'MOP',
    'MUD',
    'MUG',
    'NAP',
    'NET',
    'NEW',
    'NIT',
    'NOR',
    'NOT',
    'NOW',
    'NUN',
    'NUT',
    'OAK',
    'OAR',
    'OAT',
    'ODD',
    'OIL',
    'OLD',
    'ONE',
    'OPT',
    'ORB',
    'ORE',
    'OUR',
    'OUT',
    'OWE',
    'OWL',
    'OWN',
    'PAN',
    'PAT',
    'PAW',
    'PEA',
    'PEN',
    'PET',
    'PIE',
    'PIG',
    'PIN',
    'PIT',
    'POD',
    'POP',
    'POT',
    'PUT',
    'RAN',
    'RAT',
    'RAW',
    'RAY',
    'RED',
    'RIB',
    'RID',
    'RIG',
    'RIM',
    'RIP',
    'ROB',
    'ROD',
    'ROT',
    'ROW',
    'RUB',
    'RUG',
    'RUN',
    'RUT',
    'SAD',
    'SAP',
    'SAT',
    'SAW',
    'SAY',
    'SEA',
    'SET',
    'SEW',
    'SHE',
    'SIP',
    'SIS',
    'SIT',
    'SIX',
    'SKI',
    'SKY',
    'SLY',
    'SOB',
    'SOD',
    'SON',
    'SOP',
    'SOT',
    'SOW',
    'SPY',
    'STY',
    'SUB',
    'SUM',
    'SUN',
    'TAB',
    'TAG',
    'TAN',
    'TAP',
    'TAR',
    'TAX',
    'TEA',
    'TEN',
    'THE',
    'TIE',
    'TIN',
    'TIP',
    'TOE',
    'TON',
    'TOO',
    'TOP',
    'TOW',
    'TOY',
    'TRY',
    'TUB',
    'TUG',
    'URN',
    'USE',
    'VAN',
    'VAT',
    'VET',
    'VIA',
    'VOW',
    'WAR',
    'WAS',
    'WAX',
    'WAY',
    'WEB',
    'WED',
    'WET',
    'WHO',
    'WIG',
    'WIN',
    'WIT',
    'WOK',
    'WON',
    'WOO',
    'WOW',
    'YAM',
    'YAP',
    'YAW',
    'YES',
    'YET',
    'YEW',
    'YOU',
    'ZAP',
    'ZEN',
    'ZIP',
    'ZIT',
    'ZOO',
  ];

  // 4-letter words
  const fourLetterWords = [
    'ABLE',
    'ACHE',
    'ACID',
    'ACRE',
    'AGED',
    'AIDE',
    'ALLY',
    'ALSO',
    'BAKE',
    'BALD',
    'BALE',
    'BALL',
    'BAND',
    'BANE',
    'BARE',
    'BARK',
    'BARN',
    'BASE',
    'BATH',
    'BEAM',
    'BEAR',
    'BEAT',
    'BELL',
    'BELT',
    'BEND',
    'BEST',
    'BIKE',
    'BIRD',
    'BITE',
    'BLOW',
    'BLUE',
    'BOAT',
    'BOLD',
    'BOLT',
    'BOND',
    'BONE',
    'BOOK',
    'BORE',
    'BORN',
    'BOSS',
    'BOWL',
    'BULK',
    'BURN',
    'BUST',
    'CAFE',
    'CAGE',
    'CAKE',
    'CALF',
    'CALL',
    'CALM',
    'CAME',
    'CAMP',
    'CAPE',
    'CARD',
    'CARE',
    'CART',
    'CASE',
    'CASH',
    'CAST',
    'CAVE',
    'CHIN',
    'CHIP',
    'CITY',
    'CLAP',
    'CLAY',
    'CLIP',
    'CLUE',
    'COAL',
    'COAT',
    'CODE',
    'COIN',
    'COLD',
    'COME',
    'COOK',
    'COOL',
    'COPE',
    'COPY',
    'CORD',
    'CORE',
    'CORN',
    'COST',
    'CRAB',
    'CREW',
    'CROP',
    'CROW',
    'CURE',
    'CURL',
    'DALE',
    'DAME',
    'DAMP',
    'DARE',
    'DARK',
    'DART',
    'DASH',
    'DATA',
    'DATE',
    'DAWN',
    'DEAD',
    'DEAL',
    'DEAR',
    'DECK',
    'DEED',
    'DEEP',
    'DEER',
    'DIAL',
    'DICE',
    'DIET',
    'DIME',
    'DIRT',
    'DISH',
    'DOCK',
    'DOME',
    'DONE',
    'DOOM',
    'DOOR',
    'DOSE',
    'DOWN',
    'DRAW',
    'DREW',
    'DROP',
    'DRUM',
    'DUAL',
    'DUCK',
    'DUEL',
    'DUKE',
    'DULL',
    'DUMP',
    'DUNE',
    'DUSK',
    'DUST',
    'DUTY',
    'EACH',
    'EARN',
    'EASE',
    'EAST',
    'EASY',
    'EDGE',
    'EDIT',
    'ELSE',
    'EPIC',
    'EVEN',
    'EVER',
    'EVIL',
    'EXAM',
    'EXIT',
    'EYED',
    'FACE',
    'FACT',
    'FADE',
    'FAIL',
    'FAIR',
    'FAKE',
    'FALL',
    'FAME',
    'FANG',
    'FARE',
    'FARM',
    'FAST',
    'FATE',
    'FEAR',
    'FEAT',
    'FEED',
    'FEEL',
    'FELL',
    'FELT',
    'FILE',
    'FILL',
    'FILM',
    'FIND',
    'FINE',
    'FIRE',
    'FIRM',
    'FISH',
    'FIST',
    'FLAG',
    'FLAT',
    'FLAW',
    'FLED',
    'FLEW',
    'FLIP',
    'FLOW',
    'FOAM',
    'FOLD',
    'FOLK',
    'FOND',
    'FOOD',
    'FOOL',
    'FOOT',
    'FORD',
    'FORK',
    'FORM',
    'FORT',
    'FOUL',
    'FOUR',
    'FREE',
    'FROM',
    'FUEL',
    'FULL',
    'FUND',
    'FURY',
    'FUSE',
    'GAIN',
    'GALE',
    'GAME',
    'GANG',
    'GATE',
    'GAVE',
    'GAZE',
    'GEAR',
    'GENE',
    'GIFT',
    'GIRL',
    'GIVE',
    'GLAD',
    'GLOW',
    'GLUE',
    'GOAT',
    'GOES',
    'GOLD',
    'GOLF',
    'GONE',
    'GOOD',
    'GRAB',
    'GRAY',
    'GREW',
    'GRID',
    'GRIM',
    'GRIN',
    'GRIP',
    'GROW',
    'GULF',
    'HACK',
    'HAIL',
    'HAIR',
    'HALE',
    'HALF',
    'HALL',
    'HALT',
    'HAND',
    'HANG',
    'HARD',
    'HARE',
    'HARM',
    'HARP',
    'HATE',
    'HAUL',
    'HAVE',
    'HAWK',
    'HAZE',
    'HEAD',
    'HEAL',
    'HEAP',
    'HEAR',
    'HEAT',
    'HEEL',
    'HELD',
    'HELL',
    'HELP',
    'HERB',
    'HERD',
    'HERE',
    'HERO',
    'HIDE',
    'HIGH',
    'HIKE',
    'HILL',
    'HINT',
    'HIRE',
    'HOLD',
    'HOLE',
    'HOME',
    'HOOD',
    'HOOK',
    'HOPE',
    'HORN',
    'HOST',
    'HOUR',
    'HUGE',
    'HULL',
    'HUNT',
    'HURT',
    'ICON',
    'IDEA',
    'INCH',
    'INTO',
    'IRON',
    'ISLE',
    'ITEM',
    'JACK',
    'JADE',
    'JAIL',
    'JAKE',
    'JANE',
    'JAZZ',
    'JEST',
    'JOBS',
    'JOKE',
    'JOLT',
    'JUMP',
    'JUNE',
    'JURY',
    'JUST',
    'KEEN',
    'KEEP',
    'KEPT',
    'KICK',
    'KIDS',
    'KILL',
    'KIND',
    'KING',
    'KISS',
    'KITE',
    'KNEE',
    'KNEW',
    'KNIT',
    'KNOB',
    'KNOT',
    'KNOW',
    'LACE',
    'LACK',
    'LADS',
    'LAID',
    'LAKE',
    'LAMB',
    'LAME',
    'LAMP',
    'LAND',
    'LANE',
    'LAST',
    'LATE',
    'LAWN',
    'LAZY',
    'LEAD',
    'LEAF',
    'LEAN',
    'LEAP',
    'LEFT',
    'LEND',
    'LENS',
    'LESS',
    'LIAR',
    'LICK',
    'LIES',
    'LIFE',
    'LIFT',
    'LIKE',
    'LIMB',
    'LIME',
    'LINE',
    'LINK',
    'LION',
    'LIST',
    'LIVE',
    'LOAD',
    'LOAN',
    'LOCK',
    'LOFT',
    'LOGO',
    'LONE',
    'LONG',
    'LOOK',
    'LOOP',
    'LORD',
    'LORE',
    'LOSE',
    'LOSS',
    'LOST',
    'LOUD',
    'LOVE',
    'LUCK',
    'LUMP',
    'LUNG',
    'LURE',
    'LURK',
    'MACE',
    'MADE',
    'MAID',
    'MAIL',
    'MAIN',
    'MAKE',
    'MALE',
    'MALL',
    'MALT',
    'MANE',
    'MANY',
    'MARE',
    'MARK',
    'MASK',
    'MASS',
    'MAST',
    'MATE',
    'MAZE',
    'MEAL',
    'MEAN',
    'MEAT',
    'MEET',
    'MELT',
    'MEMO',
    'MEND',
    'MENU',
    'MERE',
    'MESH',
    'MILD',
    'MILE',
    'MILK',
    'MILL',
    'MIME',
    'MIND',
    'MINE',
    'MINT',
    'MISS',
    'MODE',
    'MOLD',
    'MOLE',
    'MOOD',
    'MOON',
    'MORE',
    'MOSS',
    'MOST',
    'MOTH',
    'MOVE',
    'MUCH',
    'MULE',
    'MUSE',
    'MUST',
    'MUTE',
    'NAIL',
    'NAME',
    'NAVY',
    'NEAR',
    'NEAT',
    'NECK',
    'NEED',
    'NEST',
    'NEWS',
    'NEXT',
    'NICE',
    'NINE',
    'NODE',
    'NONE',
    'NOON',
    'NORM',
    'NOSE',
    'NOTE',
    'NOUN',
    'OBEY',
    'ODDS',
    'OILS',
    'OKAY',
    'ONCE',
    'ONLY',
    'ONTO',
    'OPAL',
    'OPEN',
    'ORAL',
    'OVEN',
    'OVER',
    'OWED',
    'OXEN',
    'PACE',
    'PACK',
    'PAGE',
    'PAID',
    'PAIL',
    'PAIN',
    'PAIR',
    'PALE',
    'PALM',
    'PANE',
    'PARE',
    'PARK',
    'PART',
    'PASS',
    'PAST',
    'PATH',
    'PEAK',
    'PEAR',
    'PEEL',
    'PEER',
    'PICK',
    'PIER',
    'PILE',
    'PINE',
    'PIPE',
    'PLAN',
    'PLAY',
    'PLEA',
    'PLOT',
    'PLOW',
    'PLUG',
    'PLUM',
    'PLUS',
    'POEM',
    'POET',
    'POKE',
    'POLE',
    'POLL',
    'POLO',
    'POND',
    'POOL',
    'POOR',
    'POPE',
    'PORK',
    'PORT',
    'POSE',
    'POST',
    'POUR',
    'PRAY',
    'PREY',
    'PROP',
    'PULL',
    'PULP',
    'PUMP',
    'PURE',
    'PUSH',
    'RACE',
    'RACK',
    'RAGE',
    'RAID',
    'RAIL',
    'RAIN',
    'RAKE',
    'RAMP',
    'RANG',
    'RANK',
    'RARE',
    'RASH',
    'RATE',
    'RAVE',
    'READ',
    'REAL',
    'REAR',
    'REEL',
    'RENT',
    'REST',
    'RICE',
    'RICH',
    'RIDE',
    'RIFT',
    'RING',
    'RIPE',
    'RISE',
    'RISK',
    'ROAD',
    'ROAM',
    'ROAR',
    'ROBE',
    'ROCK',
    'RODE',
    'ROLE',
    'ROLL',
    'ROOF',
    'ROOM',
    'ROOT',
    'ROPE',
    'ROSE',
    'RUDE',
    'RUIN',
    'RULE',
    'RUSH',
    'RUST',
    'SAFE',
    'SAGE',
    'SAID',
    'SAIL',
    'SAKE',
    'SALE',
    'SALT',
    'SAME',
    'SAND',
    'SANE',
    'SANG',
    'SANK',
    'SAVE',
    'SEAL',
    'SEAM',
    'SEAT',
    'SEED',
    'SEEK',
    'SELF',
    'SELL',
    'SEND',
    'SENT',
    'SHED',
    'SHIP',
    'SHOE',
    'SHOP',
    'SHOT',
    'SHOW',
    'SHUT',
    'SICK',
    'SIDE',
    'SIGH',
    'SIGN',
    'SILK',
    'SINK',
    'SITE',
    'SIZE',
    'SLAM',
    'SLAP',
    'SLED',
    'SLEW',
    'SLID',
    'SLIM',
    'SLIP',
    'SLIT',
    'SLOW',
    'SLUG',
    'SNAP',
    'SNOW',
    'SOAK',
    'SOAP',
    'SOAR',
    'SOCK',
    'SOFA',
    'SOFT',
    'SOIL',
    'SOLD',
    'SOLE',
    'SOME',
    'SONG',
    'SOON',
    'SORE',
    'SORT',
    'SOUL',
    'SOUR',
    'SPAN',
    'SPAR',
    'SPIN',
    'SPIT',
    'SPOT',
    'STAR',
    'STAY',
    'STEM',
    'STEP',
    'STEW',
    'STIR',
    'STOP',
    'STUB',
    'SUCH',
    'SUIT',
    'SURE',
    'SWAN',
    'SWAP',
    'SWIM',
    'TACK',
    'TACT',
    'TAIL',
    'TAKE',
    'TALE',
    'TALL',
    'TAME',
    'TANK',
    'TAPE',
    'TART',
    'TASK',
    'TEAM',
    'TEAR',
    'TELL',
    'TEND',
    'TENT',
    'TERM',
    'TEST',
    'TEXT',
    'THAN',
    'THAT',
    'THEM',
    'THEN',
    'THIN',
    'THIS',
    'TICK',
    'TIDE',
    'TIDY',
    'TILE',
    'TILL',
    'TILT',
    'TIME',
    'TINY',
    'TIRE',
    'TOAD',
    'TOLD',
    'TOLL',
    'TOMB',
    'TONE',
    'TOOK',
    'TOOL',
    'TOPS',
    'TORE',
    'TORN',
    'TOSS',
    'TOUR',
    'TOWN',
    'TRAP',
    'TRAY',
    'TREE',
    'TREK',
    'TRIM',
    'TRIO',
    'TRIP',
    'TRUE',
    'TUBE',
    'TUCK',
    'TUNA',
    'TUNE',
    'TURN',
    'TWIN',
    'TYPE',
    'UGLY',
    'UNDO',
    'UNIT',
    'UPON',
    'URGE',
    'USED',
    'USER',
    'VALE',
    'VANE',
    'VARY',
    'VASE',
    'VAST',
    'VEIL',
    'VEIN',
    'VENT',
    'VERB',
    'VERY',
    'VEST',
    'VETO',
    'VICE',
    'VIEW',
    'VINE',
    'VOID',
    'VOLT',
    'VOTE',
    'WADE',
    'WAGE',
    'WAIT',
    'WAKE',
    'WALK',
    'WALL',
    'WAND',
    'WANT',
    'WARD',
    'WARM',
    'WARN',
    'WARP',
    'WASH',
    'WAVE',
    'WAVY',
    'WEAK',
    'WEAR',
    'WEED',
    'WEEK',
    'WELL',
    'WENT',
    'WERE',
    'WEST',
    'WHAT',
    'WHEN',
    'WHOM',
    'WIDE',
    'WIFE',
    'WILD',
    'WILL',
    'WILT',
    'WIND',
    'WINE',
    'WING',
    'WIRE',
    'WISE',
    'WISH',
    'WITH',
    'WOKE',
    'WOLF',
    'WOMB',
    'WOOD',
    'WOOL',
    'WORD',
    'WORE',
    'WORK',
    'WORM',
    'WORN',
    'WRAP',
    'WRIT',
    'YARD',
    'YARN',
    'YEAR',
    'YELL',
    'YOUR',
    'ZEAL',
    'ZERO',
    'ZINC',
    'ZONE',
    'ZOOM',
  ];

  // 5-letter words
  const fiveLetterWords = [
    'ABOUT',
    'ABOVE',
    'ABUSE',
    'ACTED',
    'ADMIT',
    'ADOPT',
    'ADULT',
    'AFTER',
    'AGAIN',
    'AGENT',
    'AGREE',
    'AHEAD',
    'ALARM',
    'ALIEN',
    'ALIGN',
    'ALIVE',
    'ALLEY',
    'ALLOT',
    'ALLOW',
    'ALTER',
    'AMAZE',
    'AMPLE',
    'ANGEL',
    'ANGER',
    'ANGLE',
    'ANKLE',
    'APART',
    'APPLE',
    'APPLY',
    'ARENA',
    'AROSE',
    'ASIDE',
    'ATLAS',
    'ATTIC',
    'AVOID',
    'AWAKE',
    'AWARD',
    'BADGE',
    'BAKER',
    'BASIC',
    'BASIN',
    'BATCH',
    'BEACH',
    'BEARD',
    'BEAST',
    'BEGIN',
    'BEING',
    'BELOW',
    'BENCH',
    'BERRY',
    'BLADE',
    'BLAME',
    'BLANK',
    'BLAST',
    'BLAZE',
    'BLEED',
    'BLEND',
    'BLESS',
    'BLIND',
    'BLINK',
    'BLOCK',
    'BLOKE',
    'BLOOD',
    'BLOWN',
    'BOARD',
    'BOAST',
    'BONUS',
    'BOOTH',
    'BOUND',
    'BRAIN',
    'BRAND',
    'BRAVE',
    'BREAD',
    'BREAK',
    'BREED',
    'BRICK',
    'BRIDE',
    'BRIEF',
    'BRING',
    'BROAD',
    'BROOK',
    'BROWN',
    'BRUSH',
    'BUILD',
    'BUILT',
    'BUNCH',
    'BURST',
    'BUYER',
    'CABIN',
    'CABLE',
    'CAMEL',
    'CANDY',
    'CARRY',
    'CATCH',
    'CAUSE',
    'CEDAR',
    'CHAIN',
    'CHAIR',
    'CHALK',
    'CHAOS',
    'CHARM',
    'CHASE',
    'CHEAP',
    'CHECK',
    'CHEER',
    'CHESS',
    'CHEST',
    'CHIEF',
    'CHILD',
    'CHILL',
    'CHINA',
    'CHOSE',
    'CIVIL',
    'CLAIM',
    'CLASS',
    'CLEAN',
    'CLEAR',
    'CLERK',
    'CLIFF',
    'CLIMB',
    'CLING',
    'CLOCK',
    'CLONE',
    'CLOSE',
    'CLOTH',
    'CLOUD',
    'COACH',
    'COAST',
    'COLOR',
    'CORAL',
    'COULD',
    'COUNT',
    'COURT',
    'COVER',
    'CRACK',
    'CRAFT',
    'CRANE',
    'CRASH',
    'CRAZY',
    'CREAM',
    'CREEK',
    'CREST',
    'CRIME',
    'CRISP',
    'CROSS',
    'CROWD',
    'CROWN',
    'CRUSH',
    'CURVE',
    'DAILY',
    'DANCE',
    'DEALT',
    'DEATH',
    'DEBUT',
    'DELAY',
    'DEMON',
    'DENSE',
    'DEPTH',
    'DERBY',
    'DEVIL',
    'DIARY',
    'DIRTY',
    'DITCH',
    'DONOR',
    'DOUBT',
    'DOZEN',
    'DRAFT',
    'DRAIN',
    'DRAKE',
    'DRAMA',
    'DRANK',
    'DRAWN',
    'DREAM',
    'DRESS',
    'DRIED',
    'DRIFT',
    'DRILL',
    'DRINK',
    'DRIVE',
    'DROWN',
    'DRUNK',
    'DYING',
    'EAGER',
    'EAGLE',
    'EARLY',
    'EARTH',
    'EATER',
    'EIGHT',
    'ELDER',
    'ELECT',
    'ELITE',
    'EMPTY',
    'ENDED',
    'ENEMY',
    'ENJOY',
    'ENTER',
    'EQUAL',
    'ERROR',
    'ESSAY',
    'EVENT',
    'EVERY',
    'EXACT',
    'EXIST',
    'EXTRA',
    'FABLE',
    'FAITH',
    'FALSE',
    'FAULT',
    'FEAST',
    'FENCE',
    'FETCH',
    'FEVER',
    'FIBER',
    'FIELD',
    'FIFTY',
    'FIGHT',
    'FINAL',
    'FIRST',
    'FIXED',
    'FLAME',
    'FLASH',
    'FLEET',
    'FLESH',
    'FLOAT',
    'FLOOD',
    'FLOOR',
    'FLOUR',
    'FLOWN',
    'FLUID',
    'FOCUS',
    'FORCE',
    'FORGE',
    'FORTH',
    'FOUND',
    'FRAME',
    'FRANK',
    'FRAUD',
    'FRESH',
    'FRONT',
    'FROST',
    'FROZE',
    'FRUIT',
    'FULLY',
    'GENRE',
    'GHOST',
    'GIANT',
    'GIVEN',
    'GLASS',
    'GLEAM',
    'GLOBE',
    'GLOOM',
    'GLORY',
    'GLOVE',
    'GOING',
    'GRACE',
    'GRADE',
    'GRAIN',
    'GRAND',
    'GRANT',
    'GRAPH',
    'GRASP',
    'GRASS',
    'GRAVE',
    'GREAT',
    'GREEN',
    'GREET',
    'GRIEF',
    'GRILL',
    'GRIND',
    'GROSS',
    'GROUP',
    'GROVE',
    'GROWN',
    'GUARD',
    'GUESS',
    'GUEST',
    'GUIDE',
    'GUILD',
    'GUILT',
    'HABIT',
    'HAPPY',
    'HARSH',
    'HASTE',
    'HAVEN',
    'HEART',
    'HEAVY',
    'HENCE',
    'HILLY',
    'HONEY',
    'HONOR',
    'HORSE',
    'HOTEL',
    'HOUSE',
    'HUMAN',
    'HUMOR',
    'HURRY',
    'IDEAL',
    'IMAGE',
    'IMPLY',
    'INDEX',
    'INDIE',
    'INNER',
    'INPUT',
    'IRONY',
    'ISSUE',
    'IVORY',
    'JEWEL',
    'JOINT',
    'JOKER',
    'JUDGE',
    'JUICE',
    'JUNCO',
    'KNACK',
    'KNEEL',
    'KNIFE',
    'KNOCK',
    'KNOWN',
    'LABEL',
    'LABOR',
    'LAKE',
    'LARGE',
    'LASER',
    'LATER',
    'LAUGH',
    'LAYER',
    'LEARN',
    'LEASE',
    'LEAST',
    'LEAVE',
    'LEGAL',
    'LEMON',
    'LEVEL',
    'LIGHT',
    'LIMIT',
    'LINEN',
    'LIVER',
    'LOCAL',
    'LOGIC',
    'LOOSE',
    'LOVER',
    'LOWER',
    'LOYAL',
    'LUNAR',
    'LUNCH',
    'MAGIC',
    'MAJOR',
    'MAKER',
    'MANOR',
    'MARCH',
    'MATCH',
    'MAYOR',
    'MEDAL',
    'MEDIA',
    'MERGE',
    'MERIT',
    'METAL',
    'METER',
    'MIGHT',
    'MINOR',
    'MINUS',
    'MODEL',
    'MONEY',
    'MONTH',
    'MORAL',
    'MOTOR',
    'MOUNT',
    'MOUSE',
    'MOUTH',
    'MOVIE',
    'MUSIC',
    'MYTH',
    'NAVAL',
    'NERVE',
    'NEVER',
    'NIGHT',
    'NOBLE',
    'NOISE',
    'NORTH',
    'NOTED',
    'NOVEL',
    'NURSE',
    'OCEAN',
    'OFFER',
    'OLIVE',
    'ONSET',
    'OPERA',
    'ORDER',
    'ORGAN',
    'OTHER',
    'OUTER',
    'OWNER',
    'OXIDE',
    'PAINT',
    'PANEL',
    'PANIC',
    'PAPER',
    'PARTY',
    'PASTE',
    'PATCH',
    'PAUSE',
    'PEACE',
    'PEARL',
    'PENNY',
    'PHASE',
    'PHONE',
    'PIANO',
    'PIECE',
    'PILOT',
    'PITCH',
    'PIXEL',
    'PLACE',
    'PLAIN',
    'PLANE',
    'PLANT',
    'PLATE',
    'PLAZA',
    'PLEAD',
    'PLUMB',
    'PLUME',
    'POINT',
    'POUND',
    'POWER',
    'PRESS',
    'PRICE',
    'PRIDE',
    'PRIME',
    'PRINT',
    'PRIOR',
    'PRIZE',
    'PROBE',
    'PROOF',
    'PROUD',
    'PROVE',
    'PSALM',
    'PULSE',
    'PUPIL',
    'PURSE',
    'QUEEN',
    'QUEST',
    'QUEUE',
    'QUIET',
    'QUITE',
    'QUOTA',
    'QUOTE',
    'RADAR',
    'RADIO',
    'RAISE',
    'RALLY',
    'RANCH',
    'RANGE',
    'RAPID',
    'REACH',
    'REALM',
    'REBEL',
    'REFER',
    'REIGN',
    'RELAX',
    'REPLY',
    'RIDER',
    'RIDGE',
    'RIFLE',
    'RIGHT',
    'RIGID',
    'RISEN',
    'RIVAL',
    'RIVER',
    'ROBIN',
    'ROBOT',
    'ROCKY',
    'ROGER',
    'ROMAN',
    'ROOST',
    'ROUND',
    'ROUTE',
    'ROYAL',
    'RUGBY',
    'RULER',
    'RURAL',
    'SAINT',
    'SALAD',
    'SAUCE',
    'SCALE',
    'SCARE',
    'SCENE',
    'SCENT',
    'SCOPE',
    'SCORE',
    'SCOUT',
    'SCREW',
    'SENSE',
    'SERVE',
    'SEVEN',
    'SHALL',
    'SHAME',
    'SHAPE',
    'SHARE',
    'SHARP',
    'SHEER',
    'SHEET',
    'SHELF',
    'SHELL',
    'SHIFT',
    'SHIRE',
    'SHIRT',
    'SHOCK',
    'SHOOT',
    'SHORT',
    'SHOUT',
    'SHOWN',
    'SHRUG',
    'SIGHT',
    'SINCE',
    'SIXTH',
    'SIXTY',
    'SKILL',
    'SKULL',
    'SLASH',
    'SLATE',
    'SLAVE',
    'SLEEP',
    'SLICE',
    'SLIDE',
    'SLOPE',
    'SMALL',
    'SMART',
    'SMELL',
    'SMILE',
    'SMITH',
    'SMOKE',
    'SNACK',
    'SNAKE',
    'SOLAR',
    'SOLID',
    'SOLVE',
    'SORRY',
    'SOUND',
    'SOUTH',
    'SPACE',
    'SPARE',
    'SPARK',
    'SPEAK',
    'SPEED',
    'SPELL',
    'SPEND',
    'SPENT',
    'SPICE',
    'SPINE',
    'SPLIT',
    'SPOKE',
    'SPOON',
    'SPORT',
    'SQUAD',
    'STACK',
    'STAFF',
    'STAGE',
    'STAIN',
    'STAIR',
    'STAKE',
    'STALE',
    'STALL',
    'STAMP',
    'STAND',
    'STARE',
    'START',
    'STATE',
    'STAYS',
    'STEAK',
    'STEAL',
    'STEAM',
    'STEEL',
    'STEEP',
    'STEER',
    'STERN',
    'STICK',
    'STIFF',
    'STILL',
    'STOCK',
    'STOLE',
    'STONE',
    'STOOD',
    'STORE',
    'STORM',
    'STORY',
    'STOVE',
    'STRAP',
    'STRAW',
    'STRIP',
    'STUCK',
    'STUDY',
    'STUFF',
    'STYLE',
    'SUITE',
    'SUNNY',
    'SUPER',
    'SURGE',
    'SWAMP',
    'SWEAR',
    'SWEEP',
    'SWEET',
    'SWEPT',
    'SWIFT',
    'SWING',
    'SWORD',
    'TABLE',
    'TASTE',
    'TEACH',
    'TEETH',
    'TENSE',
    'THEFT',
    'THEIR',
    'THEME',
    'THERE',
    'THICK',
    'THIEF',
    'THING',
    'THINK',
    'THIRD',
    'THOSE',
    'THREE',
    'THREW',
    'THROW',
    'THUMB',
    'TIGHT',
    'TIGER',
    'TIMER',
    'TITLE',
    'TODAY',
    'TOKEN',
    'TOTAL',
    'TOUCH',
    'TOUGH',
    'TOWER',
    'TOXIC',
    'TRACE',
    'TRACK',
    'TRADE',
    'TRAIL',
    'TRAIN',
    'TRAIT',
    'TRASH',
    'TREAT',
    'TREND',
    'TRIAL',
    'TRIBE',
    'TRICK',
    'TRIED',
    'TROOP',
    'TRUCE',
    'TRUCK',
    'TRULY',
    'TRUNK',
    'TRUST',
    'TRUTH',
    'TUMOR',
    'TWICE',
    'TWIST',
    'ULTRA',
    'UNCLE',
    'UNDER',
    'UNION',
    'UNITE',
    'UNITY',
    'UNTIL',
    'UPPER',
    'UPSET',
    'URBAN',
    'USAGE',
    'USUAL',
    'UTTER',
    'VALID',
    'VALUE',
    'VALVE',
    'VAPOR',
    'VAULT',
    'VENUE',
    'VERSE',
    'VIDEO',
    'VIGOR',
    'VIRAL',
    'VISIT',
    'VITAL',
    'VIVID',
    'VOCAL',
    'VOICE',
    'VOTER',
    'WATCH',
    'WATER',
    'WAVED',
    'WEARY',
    'WEAVE',
    'WHEAT',
    'WHEEL',
    'WHERE',
    'WHICH',
    'WHILE',
    'WHITE',
    'WHOLE',
    'WHOSE',
    'WIDTH',
    'WOMAN',
    'WORLD',
    'WORRY',
    'WORSE',
    'WORST',
    'WORTH',
    'WOULD',
    'WOUND',
    'WRATH',
    'WRITE',
    'WROTE',
    'YACHT',
    'YIELD',
    'YOUNG',
    'YOUTH',
    'ZEBRA',
  ];

  const allWords = [
    ...twoLetterWords.map((w) => ({ word: w, score: 30 })),
    ...threeLetterWords.map((w) => ({ word: w, score: 50 })),
    ...fourLetterWords.map((w) => ({ word: w, score: 65 })),
    ...fiveLetterWords.map((w) => ({ word: w, score: 75 })),
  ];

  index.loadFromArray(allWords);
  return index;
}

describe('CrosswordGenerator', () => {
  let testIndex;
  let masterIndex;

  beforeAll(() => {
    testIndex = buildTestIndex();
    clearWordIndexCache();
    masterIndex = getWordIndex();
  });

  // ─── Basic Unit Tests (with controlled test index) ──────────

  describe('getCandidatesForSlot (test index)', () => {
    it('should return candidates for a given slot', () => {
      const generator = new CrosswordGenerator(testIndex, {
        minScore: 1,
        timeoutMs: 10000,
      });

      const grid = Array.from({ length: 5 }, () => Array(5).fill(''));
      const result = generator.getCandidatesForSlot(grid, 'across-0-0');

      expect(result.candidates).toBeDefined();
      expect(result.candidates.length).toBeGreaterThan(0);
      expect(result.slot).toBeDefined();
      expect(result.slot.id).toBe('across-0-0');
      expect(result.slot.direction).toBe('across');
      expect(result.slot.length).toBe(5);
      expect(result.totalCandidates).toBeGreaterThan(0);

      // Each candidate should have word, wordScore, gridScore, viable
      const first = result.candidates[0];
      expect(first.word).toBeDefined();
      expect(first.wordScore).toBeDefined();
      expect(first.gridScore).toBeDefined();
      expect(typeof first.viable).toBe('boolean');
    });

    it('should return candidates constrained by existing letters', () => {
      const generator = new CrosswordGenerator(testIndex, {
        minScore: 1,
        timeoutMs: 10000,
      });

      const grid = Array.from({ length: 5 }, () => Array(5).fill(''));
      grid[0][0] = 'C';

      const result = generator.getCandidatesForSlot(grid, 'across-0-0');
      expect(result.candidates.length).toBeGreaterThan(0);

      for (const cand of result.candidates) {
        expect(cand.word[0]).toBe('C');
      }
    });

    it('should return empty for nonexistent slot', () => {
      const generator = new CrosswordGenerator(testIndex, { minScore: 1 });
      const grid = Array.from({ length: 5 }, () => Array(5).fill(''));
      const result = generator.getCandidatesForSlot(grid, 'across-99-99');
      expect(result.candidates).toHaveLength(0);
      expect(result.error).toBeDefined();
    });
  });

  describe('findBestLocation (test index)', () => {
    it('should find the most constrained slot', () => {
      const generator = new CrosswordGenerator(testIndex, {
        minScore: 1,
        timeoutMs: 10000,
      });

      const grid = Array.from({ length: 5 }, () => Array(5).fill(''));
      const result = generator.findBestLocation(grid);

      expect(result).not.toBeNull();
      expect(result.slot).toBeDefined();
      expect(result.slot.id).toBeDefined();
      expect(result.domainSize).toBeGreaterThan(0);
      expect(result.reason).toBeDefined();
    });

    it('should not select a filled slot', () => {
      const generator = new CrosswordGenerator(testIndex, {
        minScore: 1,
        timeoutMs: 10000,
      });

      const grid = Array.from({ length: 5 }, () => Array(5).fill(''));
      grid[0] = ['C', 'R', 'A', 'N', 'E'];

      const result = generator.findBestLocation(grid);
      expect(result).not.toBeNull();
      expect(result.slot.id).not.toBe('across-0-0');
    });
  });

  describe('constraint propagation', () => {
    it('should detect unsolvable grids', () => {
      const generator = new CrosswordGenerator(testIndex, {
        minScore: 1,
        maxRetries: 1,
        timeoutMs: 2000,
      });

      const grid = Array.from({ length: 5 }, () => Array(5).fill(''));
      grid[0] = ['Z', 'Z', 'Z', 'Z', 'Z'];
      grid[1] = ['Z', 'Z', 'Z', 'Z', 'Z'];

      const result = generator.quickFill(grid);
      expect(result.success).toBe(false);
    });
  });

  describe('grid score computation', () => {
    it('should compute grid scores for candidates', () => {
      const generator = new CrosswordGenerator(testIndex, {
        minScore: 1,
        timeoutMs: 10000,
      });

      const grid = Array.from({ length: 5 }, () => Array(5).fill(''));
      const result = generator.getCandidatesForSlot(grid, 'across-0-0', {
        computeGridScore: true,
        limit: 20,
      });

      expect(result.candidates.length).toBeGreaterThan(0);

      for (const cand of result.candidates) {
        expect(cand.gridScore).toBeGreaterThanOrEqual(0);
        expect(typeof cand.gridScore).toBe('number');
      }
    });
  });

  // ─── Full Integration Tests (with master dictionary) ────────

  describe('generate from scratch (master dict)', () => {
    it('should generate a valid 5x5 puzzle', () => {
      const generator = new CrosswordGenerator(masterIndex, {
        minScore: 25,
        timeoutMs: 10000,
      });

      const result = generator.generate('scratch', null, 'none');

      expect(result.success).toBe(true);
      expect(result.grid).toHaveLength(5);
      expect(result.solution).toHaveLength(5);
      expect(result.words.length).toBeGreaterThan(0);

      for (let r = 0; r < 5; r++) {
        for (let c = 0; c < 5; c++) {
          const cell = result.solution[r][c];
          expect(cell).toBeTruthy();
          if (cell !== '■') {
            expect(cell).toMatch(/^[A-Z]$/);
          }
        }
      }
    });

    it('should produce words that exist in the dictionary', () => {
      const generator = new CrosswordGenerator(masterIndex, {
        minScore: 25,
        timeoutMs: 10000,
      });

      const result = generator.generate('scratch', null, 'none');
      expect(result.success).toBe(true);

      for (const { word } of result.words) {
        expect(masterIndex.has(word)).toBe(true);
      }
    });

    it('should not reuse words within a single puzzle', () => {
      const generator = new CrosswordGenerator(masterIndex, {
        minScore: 25,
        timeoutMs: 10000,
      });

      const result = generator.generate('scratch', null, 'none');
      expect(result.success).toBe(true);

      const wordSet = new Set(result.words.map((w) => w.word));
      expect(wordSet.size).toBe(result.words.length);
    });

    it('should return quality stats', () => {
      const generator = new CrosswordGenerator(masterIndex, {
        minScore: 25,
        timeoutMs: 10000,
      });

      const result = generator.generate('scratch', null, 'none');
      expect(result.success).toBe(true);
      expect(result.stats.qualityScore).toBeDefined();
      expect(result.stats.averageWordScore).toBeDefined();
      expect(result.stats.totalAttempts).toBeGreaterThan(0);
    });
  });

  describe('fill mode with seed words (master dict)', () => {
    it('should fill around pre-placed letters', () => {
      const generator = new CrosswordGenerator(masterIndex, {
        minScore: 25,
        timeoutMs: 10000,
      });

      const seedGrid = Array.from({ length: 5 }, () => Array(5).fill(''));
      seedGrid[0] = ['C', 'R', 'A', 'N', 'E'];

      const result = generator.generate('fill', seedGrid, 'none');
      expect(result.success).toBe(true);
      expect(result.solution[0].join('')).toBe('CRANE');

      for (const { word } of result.words) {
        expect(masterIndex.has(word)).toBe(true);
      }
    });

    it('should preserve multiple seed words', () => {
      const generator = new CrosswordGenerator(masterIndex, {
        minScore: 5,
        timeoutMs: 10000,
      });

      const seedGrid = Array.from({ length: 5 }, () => Array(5).fill(''));
      seedGrid[0] = ['C', 'R', 'A', 'N', 'E'];
      seedGrid[4] = ['B', 'L', 'A', 'S', 'T'];

      const result = generator.generate('fill', seedGrid, 'none');
      expect(result.success).toBe(true);
      expect(result.solution[0].join('')).toBe('CRANE');
      expect(result.solution[4].join('')).toBe('BLAST');
    });
  });

  describe('quickFill (master dict)', () => {
    // quickFill uses randomized shuffling so we retry to ensure reliable tests
    // Helper: quickFill with retries and a grid pattern (center black square)
    // The solver works best with some black squares — a fully open 5x5 is very constrained.
    function makeGridWithPattern() {
      const grid = Array.from({ length: 5 }, () => Array(5).fill(''));
      grid[2][2] = '■'; // Center black square — common pattern
      return grid;
    }

    function quickFillReliable(index, grid, opts = {}) {
      for (let i = 0; i < 5; i++) {
        const gen = new CrosswordGenerator(index, {
          minScore: opts.minScore || 5,
          excludeWords: opts.excludeWords || [],
          timeoutMs: 10000,
        });
        const result = gen.quickFill(
          grid.map((r) => [...r]),
          opts
        );
        if (result.success) return result;
      }
      return { success: false, error: 'Failed after 5 retries' };
    }

    it('should fill a grid with center black square', () => {
      const grid = makeGridWithPattern();
      const result = quickFillReliable(masterIndex, grid);

      expect(result.success).toBe(true);
      expect(result.solution).toHaveLength(5);
      expect(result.qualityScore).toBeDefined();
      expect(result.averageWordScore).toBeDefined();
      expect(result.elapsedMs).toBeDefined();
      expect(result.solution[2][2]).toBe('■');
    });

    it('should produce different results on multiple calls', () => {
      const results = new Set();

      for (let i = 0; i < 10; i++) {
        const grid = makeGridWithPattern();
        const result = quickFillReliable(masterIndex, grid);
        if (result.success) {
          results.add(result.solution[0].join(''));
        }
      }

      // With randomness, should get at least 2 different first rows in 10 tries
      expect(results.size).toBeGreaterThanOrEqual(2);
    });

    it('should fill around existing seed letters', () => {
      const grid = makeGridWithPattern();
      grid[0] = ['S', 'T', 'A', 'R', 'E'];

      const result = quickFillReliable(masterIndex, grid);
      expect(result.success).toBe(true);
      expect(result.solution[0].join('')).toBe('STARE');
    });

    it('should respect excluded words', () => {
      const grid = makeGridWithPattern();
      const result = quickFillReliable(masterIndex, grid, {
        excludeWords: ['CRANE', 'BLAST', 'TRACE'],
      });

      if (result.success) {
        const usedWords = result.words.map((w) => w.word);
        expect(usedWords).not.toContain('CRANE');
        expect(usedWords).not.toContain('BLAST');
        expect(usedWords).not.toContain('TRACE');
      }
    });

    it('should respect minScore setting', () => {
      const grid = makeGridWithPattern();
      const result = quickFillReliable(masterIndex, grid, { minScore: 40 });

      if (result.success) {
        for (const { word } of result.words) {
          expect(masterIndex.getScore(word)).toBeGreaterThanOrEqual(40);
        }
      }
    });
  });

  describe('findBestLocation returns null for filled grid (master dict)', () => {
    it('should return null when all slots are filled', () => {
      // Use generate() which is more reliable than quickFill for testing
      const generator = new CrosswordGenerator(masterIndex, {
        minScore: 5,
        timeoutMs: 10000,
      });

      const result = generator.generate('scratch', null, 'none');
      expect(result.success).toBe(true);

      const generator2 = new CrosswordGenerator(masterIndex, { minScore: 5 });
      const bestLoc = generator2.findBestLocation(result.solution);
      expect(bestLoc).toBeNull();
    });
  });
});
